name: Auto assign to project

on:
  issues:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: [self-hosted, dockered]
    name: Assign to Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project 2
      uses: srggrs/assign-one-project-github-action@1.2.1
      with:
        project: 'https://github.com/orgs/ESKARIA/projects/11'
